const quloxLogo = `<a class="logo" href="/"><span class="logo-mark">Q</span><span>qulox</span></a>`;

function shell() {
  return `<div class="shell"><header class="nav">${quloxLogo}<nav class="nav-links"><a href="#why">Why Qulox</a><a href="#creators">For creators</a><a href="/zwolf.tv">Z-Wolf</a><a class="btn btn-primary" href="#start">Get started</a></nav></header></div>`;
}
function home() {
  document.title = 'Qulox — Create. Connect. Watch.';
  return `${shell()}<main>
    <section class="hero"><div class="hero-inner"><div><div class="eyebrow">The social hub for what’s next</div><h1>Create your world. <span class="gradient-text">Connect beyond.</span></h1><p class="lede">Qulox brings creators, communities, and curious people together. Share your story, discover your people, and make something worth watching.</p><div class="hero-actions"><button class="btn btn-dark" data-toast="Welcome to Qulox">Join Qulox free →</button><a class="btn btn-outline" href="/zwolf.tv">Explore Z-Wolf</a></div></div><div class="art"><div class="art-card art-main"></div><div class="art-card art-small"></div></div></div></section>
    <div class="stats"><div class="stat"><strong>1M+</strong><span>ideas shared</span></div><div class="stat"><strong>80K</strong><span>creators growing</span></div><div class="stat"><strong>24/7</strong><span>live connection</span></div></div>
    <section class="section" id="why"><div class="section-heading"><div class="eyebrow">One platform, your way</div><h2>More than a feed.</h2><p>Qulox is built for real connection — whether you’re finding your next favorite creator or building a community around the things you love.</p></div><div class="cards"><article class="card"><div class="card-icon">✦</div><h3>Make it yours</h3><p>Post videos, music, shorts, and ideas. Your profile is your creative home base.</p></article><article class="card"><div class="card-icon">◎</div><h3>Find your people</h3><p>Follow the conversations and creators that make you feel inspired, seen, and connected.</p></article><article class="card"><div class="card-icon">↗</div><h3>Grow together</h3><p>Build an audience, collaborate with brands, and turn momentum into opportunity.</p></article></div></section>
    <section class="section split" id="creators"><div><div class="eyebrow" style="color:#b9f56d">Built for every kind of creator</div><h2>Make your next thing your biggest thing.</h2><p>From your first upload to your hundredth thousand views, Qulox gives creators a place to experiment, connect, and grow — without losing the human part.</p><div class="feature-list"><div><span class="check">✓</span> Share video, music, and live moments</div><div><span class="check">✓</span> Discover your audience with insights</div><div><span class="check">✓</span> Switch to a business profile anytime</div></div></div><div class="dual-preview"><div class="preview-bar"><span class="dot"></span><span class="dot"></span><span class="dot"></span></div><div class="preview-content"><div class="mock"></div><div><div class="mock side"></div><div class="mock side" style="margin-top:10px"></div></div></div></div></section>
    <section class="cta" id="start"><h2>Your people are already here.</h2><p>Join a more creative, more connected social experience — and make a space that feels like yours.</p><button class="btn btn-dark" data-toast="Your Qulox invite is ready">Create your account →</button></section>
  </main><footer class="footer">${quloxLogo}<span>© 2026 Qulox · Community guidelines · Privacy · Safety</span></footer>`;
}
function zwolf() {
  document.title = 'Z-Wolf — Premium streaming';
  return `<div class="zwolf"><header class="nav">${quloxLogo}<nav class="nav-links"><a href="/">Back to Qulox</a><a href="#browse">Browse</a><a href="#my-list">My list</a><button class="btn btn-primary" data-toast="Sign in coming soon">Sign in</button></nav></header><main><section class="zwolf-hero"><div class="eyebrow" style="color:#ff6372">Qulox presents</div><h1>Stories with a little more <span style="color:#de1f35">bite.</span></h1><p>Premium films, indie originals, and series worth staying up for. Curated by people, not an algorithm.</p><div class="hero-actions"><button class="btn btn-primary" data-toast="Playback demo ready">▶ Play featured</button><button class="btn btn-outline" style="color:white;border-color:#5b5d6b" data-toast="Added to your list">＋ My list</button></div></section><section class="catalog" id="browse"><div class="eyebrow" style="color:#ff6372">The catalog</div><h2>Popular on Z-Wolf</h2><div class="show-grid"><article class="show"><b>After the Signal</b><small>Drama · 2026</small></article><article class="show"><b>Neon Valley</b><small>Series · 2 seasons</small></article><article class="show"><b>Wild Current</b><small>Documentary · 4K</small></article><article class="show"><b>Last Light</b><small>Original film</small></article></div></section></main></div>`;
}
function admin() {
  return `<div class="admin"><div class="admin-panel"><div style="display:flex;justify-content:space-between;align-items:center;gap:20px"><div><div class="eyebrow">Super-admin only</div><h1 style="font-size:42px;margin:10px 0">Content control center</h1><p style="color:var(--muted)">Z-Wolf catalog ingest · demo interface</p></div><a class="btn btn-outline" href="/">Exit</a></div><table class="admin-table"><thead><tr><th>Title</th><th>Source</th><th>Rights</th><th>State</th></tr></thead><tbody><tr><td>After the Signal</td><td>Studio portal</td><td>Worldwide · 2028</td><td><span class="pill">Published</span></td></tr><tr><td>Wild Current</td><td>Distributor API</td><td>US / CA · 2027</td><td><span class="pill">Published</span></td></tr><tr><td>New catalog item</td><td><button class="btn btn-primary" data-toast="Secure ingest form opened">＋ Secure ingest</button></td><td>—</td><td>Draft</td></tr></tbody></table></div></div>`;
}
const path = window.location.pathname;
document.getElementById('app').innerHTML = path === '/zwolf.tv' ? zwolf() : path === '/admin' ? admin() : home();
document.addEventListener('click', event => { const button = event.target.closest('[data-toast]'); if (!button) return; const toast = document.createElement('div'); toast.textContent = button.dataset.toast; toast.style.cssText='position:fixed;bottom:25px;left:50%;transform:translateX(-50%);background:#07141f;color:white;padding:14px 20px;border-radius:999px;z-index:10;box-shadow:0 8px 30px #0003'; document.body.appendChild(toast); setTimeout(()=>toast.remove(),2600); });
